version: 2

updates:
  - package-ecosystem: bundler
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    commit-message:
      prefix: 'build:'
    open-pull-requests-limit: 6
    reviewers:
      - johnallen3d
    assignees:
      - johnallen3d
