FROM ruby:alpine

ARG HOST_PATH

ENV COMPOSE_VERSION 1.7.1

RUN \
  apk add --update \
    docker \
    py-pip \
    py-yaml && \
  pip install -U docker-compose==${COMPOSE_VERSION} && \
  rm /var/cache/apk/* && \
  rm -rf `find / -regex '.*\.py[co]' -or -name apk`

WORKDIR $HOST_PATH

COPY Gemfile* $HOST_PATH/
COPY VERSION $HOST_PATH/VERSION
COPY lib/nib/version.rb $HOST_PATH/lib/nib/version.rb
COPY nib.gemspec $HOST_PATH

RUN \
  gem install bundler && \
  bundle install -j4

COPY . $HOST_PATH

COPY spec/bin/nibtest /usr/local/bin

CMD rspec spec
