FROM ruby:alpine

ENV COMPOSE_VERSION 1.7.1

RUN \
  apk add --update \
    build-base \
    docker \
    libffi-dev \
    py-pip \
    py-yaml && \
  pip install -U docker-compose==${COMPOSE_VERSION} && \
  rm /var/cache/apk/* && \
  rm -rf `find / -regex '.*\.py[co]' -or -name apk`

WORKDIR /usr/src/app

COPY Gemfile* ./
COPY VERSION ./VERSION
COPY lib/nib/version.rb ./lib/nib/version.rb
COPY nib.gemspec ./nib.gemspec

RUN \
  gem install bundler && \
  bundle install -j4

COPY . .

COPY spec/bin/nibtest /usr/local/bin

CMD rspec spec
