version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          # pinned to work around incompatibilities between older Docker
          # runtimes and Alpine
          # https://github.com/docker-library/ruby/issues/351#issuecomment-899096462
          version: 20.10.11

      - run:
          name: Setup Code Climate test-reporter
          command: |
            cc_download_url=https://codeclimate.com/downloads/test-reporter/
            curl -L $cc_download_url/test-reporter-latest-linux-amd64 > ./cc
            chmod +x ./cc

      - run:
          name: Build the image(s)
          command: |
            docker-compose build

      - run:
          name: Run tests
          command: |
            set -x
            # notify code climate that a build is starting
            ./cc before-build
            # run the specs
            docker-compose run --name=tests ci
            # copy coverage results out of the container
            docker cp tests:/usr/src/app/coverage ./coverage
            # notify code climate build is finished
            ./cc after-build -t simplecov

      - run:
          name: Run danger checks
          command: |
            danger --verbose

      - store_artifacts:
          path: ./coverage
