require 'nib/version'

require 'nib/code_climate'
require 'nib/console'
require 'nib/debug'
require 'nib/exec'
require 'nib/run'
require 'nib/setup'
require 'nib/shell'
require 'nib/update'
require 'nib/wrap_command'
