#!/bin/bash
#
# Start a repl for the given container
#
#/* vim: set filetype=sh : */

show_help() {
  echo "$(print_common_usage "$COMMAND")

$(print_command_instructions)

Options:
  -e, --env   Environment name (default: development)
  -h          Print usage

Services:
$(print_services)"
}

DIR=/bin/script

source "$DIR/common"
source "$DIR/_help"

ENVIRONMENT="development"
SERVICE="$1"

local_history_path="${PWD}/tmp"
local_history_file="${local_history_path}/shell_history"
mkdir -p $local_history_path
touch $local_history_file

docker-compose run \
  --rm \
  -e HISTFILE=/usr/src/app/tmp/shell_history \
  $SERVICE \
  /bin/sh -c "${SCRIPT}"
