#!/bin/bash
#
# Start a repl for the given container
#
#/* vim: set filetype=sh : */

SCRIPT="
  if hash rails 2>/dev/null ; then
    rails console
  elif hash pry 2>/dev/null ; then
    pry -r ./config/boot.rb
  elif hash bundle 2>/dev/null ; then
    bundle console
  else
    script/console
  fi
"

source "/bin/script/_tty"
