#!/bin/bash
#
# Start a bash session for the given service
#
#/* vim: set filetype=sh : */

SCRIPT="
  if hash bash 2>/dev/null ; then
    bash
  elif hash ash 2>/dev/null ; then
    ash
  else
    sh
  fi
"

source "/bin/script/_tty"
