name: Lint and Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.0', '3.1']

    steps:
    - uses: actions/checkout@v2

    - name: Set Ruby Version
      run: sed -i 's/:3.1-alpine/:${{ matrix.ruby }}-alpine/' Dockerfile

    - name: Build
      run: docker-compose -p ci build --pull
      env:
        COMPOSE_DOCKER_CLI_BUILD: 1
        DOCKER_BUILDKIT: 1

    - name: Test
      run: docker-compose -p ci run --name=test gem rake rspec:unit

    - name: Lint
      if: matrix.ruby  == '3.1'
      run: docker-compose -p ci run --name=lint gem rubocop .

    - name: Archive code coverage results
      if: matrix.ruby  == '3.1'
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: ./coverage

    - name: Report on coverage
      if: matrix.ruby  == '3.1'
      uses: aki77/simplecov-report-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        failedThreshold: 93
