name: Lint and Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: docker-compose -p ci build --pull
      env:
        COMPOSE_DOCKER_CLI_BUILD: 1
        DOCKER_BUILDKIT: 1

    - name: Test
      run: docker-compose -p ci run --name=test test

    - name: Lint
      run: docker-compose -p ci run --name=lint lint

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: ./coverage

    - name: Report on coverage
      uses: aki77/simplecov-report-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        failedThreshold: 93
