on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Gem
    uses: telus-agcg/ci-pipeline-templates/.github/workflows/docker-deploy-gem-template.yml@version/1.4
    with:
      gemDirectory: "./"
      gemService: "ci"
      sourceOwner: "telus-agcg"
      dryRun: false
    secrets:
      encryptionKey: ${{ secrets.ENCRYPTION_KEY }}
      buildArgs: ${{ secrets.BUILD_ARGS }}
      githubToken: ${{ secrets.GITHUB_TOKEN }}
